apiVersion: v1
kind: Secret
metadata:
  name: seatlock-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: seatlock
  SPRING_DATASOURCE_PASSWORD: seatlockpassword
  POSTGRES_USER: seatlock
  POSTGRES_PASSWORD: seatlockpassword
  POSTGRES_DB: seatlock
